<?php $this->headScript()->appendFile($this->assetUrl('vendor/jstree/jstree.min.js', 'Omeka')); ?>
<?php $this->headLink()->appendStylesheet($this->assetUrl('css/jstree.css', 'Omeka')); ?>
<?php echo $this->pageTitle($this->translate('Item Sets Tree')); ?>

<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formRow($form->get('form_csrf')); ?>
<div id="page-actions">
    <button type="submit"><?php echo $this->translate('Save'); ?></button>
</div>

<?php $sorting_method = $this->setting('itemsetstree_sorting_method', 'title'); ?>
<?php if ($sorting_method === 'title'): ?>
<?php endif; ?>

<div id="tree">
<?php $itemSetsTree = $this->itemSetsTree()->getItemSetsTree(null, ['sorting_method' => 'none']); ?>
<?php echo $this->partial('item-sets-tree/item-sets-tree', ['itemSetsTree' => $itemSetsTree]); ?>
</div>

<?php echo $this->form()->closeTag(); ?>

<script>
$(document).ready(function () {
    const tree = $('#tree');
    tree.jstree({
        core: {
            check_callback: true,
        },
        dnd: {
            copy: false,
        },
        plugins: ['dnd'],
    }).on('ready.jstree', function() {
        console.log('foof');
        // Open all nodes by default.
        tree.jstree(true).open_all();
    }).on('move_node.jstree', function(e, data) {
        // Open node after moving it.
        var parent = tree.jstree(true).get_node(data.parent);
        tree.jstree(true).open_all(parent);
    });

    $('#item-sets-tree-form').on('submit', function () {
        $('<input>', {
            'type': 'hidden',
            'name': 'jstree',
            'val': JSON.stringify(tree.jstree(true).get_json())
        }).appendTo(this);
    });
});
</script>
