<div class="meta-group">
    <h4><?php echo $this->translate('Parent item set'); ?></h4>
    <div class="value">
        <?php $parentItemSet = $this->itemSetsTree()->getParent($itemSet); ?>
        <?php if ($parentItemSet): ?>
            <?php echo $parentItemSet->link($parentItemSet->displayTitle()); ?>
        <?php else: ?>
            <?php echo $this->translate('This item set has no parent item set') ?>
        <?php endif; ?>
    </div>
</div>
